// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hywomzzskbjtyjdtmvzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5d29tenpza2JqdHlqZHRtdnpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyMjYzMTEsImV4cCI6MjA1MzgwMjMxMX0.lDOTgSy3gpdELourSSD-5Sw-Y7lSiGBtiMkpfQK6gis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);